export const ALL_FAQS_SUCCESS = "ALL_FAQS_SUCCESS";
export const ALL_FAQS_FAIL = "ALL_FAQS_FAIL";
export const FAQS_DETAILS_SUCCESS = "FAQS_DETAILS_SUCCESS";
export const FAQS_DETAILS_FAIL = "FAQS_DETAILS_FAIL";

export const FAQS_ADD_SUCCESS = "FAQS_ADD_SUCCESS";
export const FAQS_ADD_FAIL = "FAQS_ADD_FAIL";

export const FAQ_DELETE_SUCCESS = "FAQ_DELETE_SUCCESS";
export const FAQ_DELETE_FAIL = "FAQ_DELETE_FAIL";

export const FAQ_DETAILS_SUCCESS = "FAQ_DETAILS_SUCCESS";
export const FAQ_DETAILS_FAIL = "FAQ_DETAILS_FAIL";

export const FAQ_UPDATE_SUCCESS = "FAQ_UPDATE_SUCCESS";
export const FAQ_UPDATE_FAIL = "FAQ_UPDATE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";